/**
 * GitHub Pages Integration for prototype deployments
 * 
 * Requirements:
 * - GITHUB_TOKEN in .env (with repo scope)
 * - GITHUB_REPO (optional, defaults to user's prototype-repo)
 */

interface GitHubPagesResult {
  success: boolean;
  url?: string;
  error?: string;
}

/**
 * Deploy HTML prototype to GitHub Pages
 */
export async function deployToGitHubPages(
  productName: string,
  htmlContent: string,
  slug: string
): Promise<GitHubPagesResult> {
  const token = process.env.GITHUB_TOKEN;

  if (!token) {
    console.log('[GitHub Pages] No GITHUB_TOKEN configured');
    return {
      success: false,
      error: 'GITHUB_TOKEN not configured'
    };
  }

  try {
    // Get authenticated user
    const userResponse = await fetch('https://api.github.com/user', {
      headers: {
        'Authorization': `token ${token}`,
        'Accept': 'application/vnd.github.v3+json'
      }
    });

    if (!userResponse.ok) {
      return { success: false, error: 'Failed to authenticate with GitHub' };
    }

    const user = await userResponse.json();
    const owner = user.login;
    const repoName = 'intuiux-prototypes';

    console.log(`[GitHub Pages] Deploying as user: ${owner}`);

    // Check if repo exists, create if not
    const repoCheck = await fetch(`https://api.github.com/repos/${owner}/${repoName}`, {
      headers: {
        'Authorization': `token ${token}`,
        'Accept': 'application/vnd.github.v3+json'
      }
    });

    if (!repoCheck.ok) {
      // Create the repository
      console.log(`[GitHub Pages] Creating repository ${repoName}...`);
      const createRepo = await fetch('https://api.github.com/user/repos', {
        method: 'POST',
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: repoName,
          description: 'Prototypes generated by IntuiUX Agent',
          private: false,
          auto_init: true
        })
      });

      if (!createRepo.ok) {
        const error = await createRepo.json();
        console.error('[GitHub Pages] Failed to create repo:', error);
        return { success: false, error: 'Failed to create repository' };
      }

      // Wait a bit for repo to be created
      await new Promise(r => setTimeout(r, 2000));

      // Enable GitHub Pages
      await fetch(`https://api.github.com/repos/${owner}/${repoName}/pages`, {
        method: 'POST',
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          source: { branch: 'main', path: '/' }
        })
      });
    }

    // Create the HTML file
    const fileName = `prototypes/${slug}/index.html`;
    const fileContent = Buffer.from(htmlContent).toString('base64');

    // Check if file exists to get its SHA
    let sha: string | undefined;
    const fileCheck = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/${fileName}`,
      {
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json'
        }
      }
    );

    if (fileCheck.ok) {
      const existingFile = await fileCheck.json();
      sha = existingFile.sha;
    }

    // Create or update the file
    const commitResponse = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/${fileName}`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          message: `Deploy prototype: ${productName}`,
          content: fileContent,
          ...(sha && { sha }),
          branch: 'main'
        })
      }
    );

    if (!commitResponse.ok) {
      const error = await commitResponse.json();
      console.error('[GitHub Pages] Failed to commit file:', error);
      return { success: false, error: 'Failed to commit file' };
    }

    // Also create an index that lists all prototypes
    await updatePrototypesIndex(token, owner, repoName, productName, slug);

    const pagesUrl = `https://${owner}.github.io/${repoName}/prototypes/${slug}/`;
    console.log(`[GitHub Pages] Deployed to: ${pagesUrl}`);

    return {
      success: true,
      url: pagesUrl
    };

  } catch (error) {
    console.error('[GitHub Pages] Deployment error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * Update the prototypes index page
 */
async function updatePrototypesIndex(
  token: string,
  owner: string,
  repoName: string,
  productName: string,
  slug: string
): Promise<void> {
  try {
    // For simplicity, just create a simple redirect index
    const indexContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>IntuiUX Prototypes</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
           background: #0a0a0f; color: #fff; min-height: 100vh; margin: 0; padding: 40px; }
    h1 { color: #FACC15; }
    ul { list-style: none; padding: 0; }
    li { margin: 10px 0; }
    a { color: #60a5fa; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>🎨 IntuiUX Prototypes</h1>
  <p>Prototypes generated by IntuiUX Agent</p>
  <ul>
    <li><a href="prototypes/${slug}/">${productName}</a></li>
  </ul>
</body>
</html>`;

    const fileContent = Buffer.from(indexContent).toString('base64');

    // Check if index exists
    let sha: string | undefined;
    const fileCheck = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/index.html`,
      {
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json'
        }
      }
    );

    if (fileCheck.ok) {
      const existingFile = await fileCheck.json();
      sha = existingFile.sha;
    }

    await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/index.html`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          message: 'Update prototypes index',
          content: fileContent,
          ...(sha && { sha }),
          branch: 'main'
        })
      }
    );
  } catch (error) {
    console.error('[GitHub Pages] Index update error:', error);
  }
}

/**
 * Check if GitHub is configured
 */
export function isGitHubConfigured(): boolean {
  return !!process.env.GITHUB_TOKEN;
}
